name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # update to latest

      - name: Setup Pages
        uses: actions/configure-pages@v4 # update to latest

      - name: Upload site files
        uses: actions/upload-pages-artifact@v2
        with:
          path: . # upload everything (index.html, css, js)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # update to latest
